### ISSUE TITLE
openapi-response-validator crashes on example: null

### ISSUE THREAD

**Issue by jharting** [kogosoftwarellc/open-api#413]
Having a spec

```yaml
---
openapi: 3.0.0

info:
  title: bug
  version: 0.1.0

paths:
  /foo:
    get:
      operationId: foo
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  foo:
                    type: string
                    nullable: true
                    example: null
```

and openapi-response-validator set up like this:

```js
'use strict';

const fs = require('fs');
const jsyaml = require('js-yaml');
const spec = jsyaml.safeLoad(fs.readFileSync('openapi.yaml', 'utf8'));

const OpenAPIResponseValidator = require('openapi-response-validator').default;

new OpenAPIResponseValidator({
    responses: spec.paths['/foo'].get.responses,
    components: spec.components
});
```

I am getting
```
/home/jharting/insights/openapi-bug-validator/node_modules/openapi-response-validator/dist/index.js:129
    if (object.type && object.nullable === true) {
               ^

TypeError: Cannot read property 'type' of null
    at recursiveTransformOpenAPIV3Definitions (/home/jharting/insights/openapi-bug-validator/node_modules/openapi-response-validator/dist/index.js:129:16)
    at /home/jharting/insights/openapi-bug-validator/node_modules/openapi-response-validator/dist/index.js:135:13
    at Array.forEach (<anonymous>)
    at recursiveTransformOpenAPIV3Definitions (/home/jharting/insights/openapi-bug-validator/node_modules/openapi-response-validator/dist/index.js:133:25)
    at /home/jharting/insights/openapi-bug-validator/node_modules/openapi-response-validator/dist/index.js:135:13
    at Array.forEach (<anonymous>)
    at recursiveTransformOpenAPIV3Definitions (/home/jharting/insights/openapi-bug-validator/node_modules/openapi-response-validator/dist/index.js:133:25)
    at /home/jharting/insights/openapi-bug-validator/node_modules/openapi-response-validator/dist/index.js:135:13
    at Array.forEach (<anonymous>)
    at recursiveTransformOpenAPIV3Definitions (/home/jharting/insights/openapi-bug-validator/node_modules/openapi-response-validator/dist/index.js:133:25)
```

during application startup.

**Comment by jsdevel** [comment]
@jharting please submit a PR
