### ISSUE TITLE
How to disable console logging entirely (express-openapi)?

### ISSUE THREAD

**Issue by TitaniteSlab** [kogosoftwarellc/open-api#685]
I see #61 but I still don't understand how.

Specifically, when `Content-Type` is provided but invalid, I'm getting a stack trace in my server console:

```
failed to parse content-type foo TypeError: invalid media type
    at Object.parse (/foo/node_modules/content-type/index.js:126:11)
    at getSchemaForMediaType (/foo/node_modules/openapi-request-validator/index.ts:385:37)
    at OpenAPIRequestValidator.validateRequest (/foo/node_modules/openapi-request-validator/index.ts:257:30)
    at requestValidatorMiddleware (/foo/node_modules/express-openapi/index.ts:132:48)
    ... more lines
```

How do I get rid of this? I want to use a noop logger.

**Comment by TitaniteSlab** [comment]
```
import { initialize } from 'express-openapi';
initialize({
  logger: {
    error: () => {},
    warn: () => {},
    info: () => {},
    debug: () => {}
  },
  ...
});
```

Seems to work.

**Comment by jsdevel** [comment]
it'd be nice to have logger: null support though to just disable it entirely

**Comment by jsdevel** [comment]
or logger: false

**Comment by jsau-** [comment]
Could use `dummyLogger` from `ts-log`. Already used in [`openapi-request-validator`](https://github.com/kogosoftwarellc/open-api/blob/v10.1.0/packages/openapi-request-validator/index.ts#L57) as a default, and it's installed in [`openapi-framework`](https://github.com/kogosoftwarellc/open-api/blob/v10.1.0/packages/openapi-framework/package.json#L41).

If `null` were to be supported at library-level to disable logging entirely it'd probably easiest be done as:

* Change type of [`logger` on `OpenAPIFrameworkArgs`](https://github.com/kogosoftwarellc/open-api/blob/v10.1.0/packages/openapi-framework/src/types.ts#L103) from `?: Logger` to `?: Logger | null`
* Change the way [`this.logger` is set on class `OpenAPIFramework`](https://github.com/kogosoftwarellc/open-api/blob/v10.1.0/packages/openapi-framework/index.ts#L94) to:

```
if (args.logger) {
  this.logger = args.logger;
} else if (args.logger !== null) {
  this.logger = new ConsoleDebugAdapterLogger();
} else {
  this.logger = dummyLogger;
}
```

Can't really see any meaningful way of checking this in the test suite though beyond adding cases that instantiate `OpenAPIFramework` with `null` and `undefined` values for `logger` to assert it doesn't throw though since the `logger` member is private and we wouldn't be able to check what it's an `instanceof` / if it's exactly the `dummyLogger`. 

@jsdevel  Can you let me know if you're happy with this solution as-is or if you'd want any extra changes made? e.g. Adding a public getter for the logger to check its type in tests, etc. I'll be happy to put a PR in for this when I get some time this week.
